DatasetAttribution:
  - "© by Brockmann Consult GmbH 2024, contains modified Copernicus Data 2019, processed by ESA"

DataStores:
  - Identifier: local_datasets
    StoreId: file
    Datasets:
      - Path: cube.nc
        Title: NetCDF file
        Identifier: netcdf_file
      - Path: cube-1-250-250.zarr
        Title: zarr file
        Identifier: zarr_file
      - Path: sample-geotiff.tif
        Title: GeoTIFF file
        Identifier: geotiff_file
      - Path: sample-cog.tif
        Title: Cloud-optimized GeoTIFF file
        Identifier: cog_geotiff_file

ServiceProvider:
  ProviderName: Brockmann Consult GmbH
  ProviderSite: https://www.brockmann-consult.de
  ServiceContact:
    IndividualName: Norman Fomferra
    PositionName: Senior Software Engineer
    ContactInfo:
      Phone:
        Voice: +49 40 696 389 300
        Facsimile: +49 40 696 389 399
      Address:
        DeliveryPoint: Chrysanderstr. 1
        City: Hamburg
        AdministrativeArea: Hamburg
        PostalCode: 21029
        Country: Germany
        ElectronicMailAddress: info@brockmann-consult.de
