DatasetAttribution:
  - "© by Brockmann Consult GmbH 2024"

DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: stac
    StoreId: stac
    StoreParams:
      url: https://earth-search.aws.element84.com/v1
      stack_mode: True
    Datasets:
      - Identifier: Sentinel-2 L2a
        Path: sentinel-2-l2a
        StoreOpenParams:
          bbox: [9, 47, 10, 48]
          time_range: ["2020-07-01", "2020-07-31"]
          bands: ["red", "green", "blue"]
          groupby: "time"
          chunks: {"time": 1, "x": 2048, "y": 2048}
        Style: S2L2A

Styles:
  - Identifier: S2L2A
    ColorMappings:
      red:
        ColorBar: "viridis"
        ValueRange: [0., 3000.]
      green:
        ColorBar: "viridis"
        ValueRange: [0., 3000.]
      blue:
        ColorBar: "viridis"
        ValueRange: [0., 3000.]
      rgb:
        Red:
          Variable: red
          ValueRange: [0., 3000.]
        Green:
          Variable: green
          ValueRange: [0., 3000.]
        Blue:
          Variable: blue
          ValueRange: [0., 3000.]

ServiceProvider:
  ProviderName: "Brockmann Consult GmbH"
  ProviderSite: "https://www.brockmann-consult.de"
  ServiceContact:
    IndividualName: "Norman Fomferra"
    PositionName: "Senior Software Engineer"
    ContactInfo:
      Phone:
        Voice: "+49 4152 889 303"
        Facsimile: "+49 4152 889 330"
      Address:
        DeliveryPoint: "HZG / GITZ"
        City: "Geesthacht"
        AdministrativeArea: "Herzogtum Lauenburg"
        PostalCode: "21502"
        Country: "Germany"
        ElectronicMailAddress: "norman.fomferra@brockmann-consult.de"
