name: Build

on:
  push:
  release:
    types: [published]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout xcube
        uses: actions/checkout@v4
        with:
          repository: xcube-dev/xcube
          path: xcube

      - name: checkout xcube-stac
        uses: actions/checkout@v4
        with:
          path: xcube-stac

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: xcube-stac/environment_workflow.yml

      - name: Install xcube
        shell: bash -l {0}
        run: |
          cd /home/runner/work/xcube-stac/xcube-stac/xcube
          ls
          pip install .

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          cd /home/runner/work/xcube-stac/xcube-stac/xcube-stac
          ls
          pytest 
